//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestersErrorLog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestersEntities : DbContext
    {
        public TestersEntities()
            : base("name=TestersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ErrorLog_NormansToyota> tbl_ErrorLog_NormansToyota { get; set; }
        public virtual DbSet<tbl_ErrorLog_PalmMotors> tbl_ErrorLog_PalmMotors { get; set; }
        public virtual DbSet<tbl_ErrorLog_RoyceLoveNissan> tbl_ErrorLog_RoyceLoveNissan { get; set; }
        public virtual DbSet<tbl_ErrorLog_WeissVolkswagenDurban> tbl_ErrorLog_WeissVolkswagenDurban { get; set; }
        public virtual DbSet<tbl_ErrorLog_AudiCentreBloemfontein> tbl_ErrorLog_AudiCentreBloemfontein { get; set; }
        public virtual DbSet<tbl_ErrorLog_iXOnlineMotoring> tbl_ErrorLog_iXOnlineMotoring { get; set; }
        public virtual DbSet<tbl_ErrorLog_LindsaySakerAlberton> tbl_ErrorLog_LindsaySakerAlberton { get; set; }
        public virtual DbSet<tbl_ErrorLog_AutohausCenturion> tbl_ErrorLog_AutohausCenturion { get; set; }
        public virtual DbSet<tbl_ErrorLog_BaronsBellville> tbl_ErrorLog_BaronsBellville { get; set; }
        public virtual DbSet<tbl_ErrorLog_BaronsBruma> tbl_ErrorLog_BaronsBruma { get; set; }
        public virtual DbSet<tbl_ErrorLog_BaronsCulemborg> tbl_ErrorLog_BaronsCulemborg { get; set; }
        public virtual DbSet<tbl_ErrorLog_BenoniCiti> tbl_ErrorLog_BenoniCiti { get; set; }
        public virtual DbSet<tbl_ErrorLog_Boat_A_Rama> tbl_ErrorLog_Boat_A_Rama { get; set; }
        public virtual DbSet<tbl_ErrorLog_ClaremontVolkswagen> tbl_ErrorLog_ClaremontVolkswagen { get; set; }
        public virtual DbSet<tbl_ErrorLog_ConsolidatedAuto> tbl_ErrorLog_ConsolidatedAuto { get; set; }
        public virtual DbSet<tbl_ErrorLog_HymanCars> tbl_ErrorLog_HymanCars { get; set; }
        public virtual DbSet<tbl_ErrorLog_LindsaySakerBloemfonteinVW> tbl_ErrorLog_LindsaySakerBloemfonteinVW { get; set; }
        public virtual DbSet<tbl_ErrorLog_ShadesAutoRepairscc> tbl_ErrorLog_ShadesAutoRepairscc { get; set; }
    }
}
